name: "Version Check + Publish to PSGallery"
on:
  push:
    branches:
      - "main"

jobs:
  run:
    name: Version Check and Publish
    runs-on: ubuntu-latest
    steps:
      - run: ./build/build.ps1 -DoNotPublish
        shell: pwsh